
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jun 05 22:47:09 CST 2024
//----------------------------------------------------

package fes.aragon.compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ABAJO = 7;
  public static final int FINREPETIR = 3;
  public static final int ARRIBA = 6;
  public static final int IZQUIERDA = 8;
  public static final int EOF = 0;
  public static final int NUMERO = 10;
  public static final int DERECHA = 9;
  public static final int error = 1;
  public static final int COLOCA = 2;
  public static final int MOVER = 5;
  public static final int REPETIR = 4;
}

